#ifndef INGREDIENTE_H
#define INGREDIENTE_H

enum E_Ingrediente
{
	E_INGREDIENT_BLAT = 2,
	E_INGREDIENT_SOS = 1,
	E_INGREDIENT_MOZZARELA = 3,
	E_INGREDIENT_ANANAS = 3,
	E_INGREDIENT_SUNCA = 3,
	E_INGREDIENT_SALAM = 4
};

#endif